participants:
  - el_type: geth
    el_image: jihoonsg/geth-focil:dffb273
    cl_type: lighthouse
    cl_image: jihoonsg/lighthouse-focil:619d1d0
    count: 2
network_params:
  genesis_delay: 20
  electra_fork_epoch: 0
  eip7805_fork_epoch: 1
  seconds_per_slot: 6
  num_validator_keys_per_node: 256
snooper_enabled: true
additional_services:
  - dora
  - tx_fuzz
  - spamoor
dora_params:
  image: ethpandaops/dora:eip7805-support-latest
port_publisher:
  additional_services:
    enabled: true
    public_port_start: 65500
spamoor_params:
  spammers:
    - scenario: eoatx
      config:
        throughput: 100
    - scenario: uniswap-swaps
      config:
        throughput: 100
    - scenario: blob-combined
      config:
        throughput: 5
