participants:
  - el_type: geth
    el_image: jihoonsg/geth-focil:6d6c343
    cl_type: prysm
    cl_image: jihoonsg/prysm-beacon-chain-focil:f48b56a
    vc_type: prysm
    vc_image: jihoonsg/prysm-validator-focil:f48b56a
  - el_type: geth
    el_image: jihoonsg/geth-focil:6d6c343
    cl_type: lodestar
    cl_image: ethpandaops/lodestar:focil
network_params:
  genesis_delay: 20
  electra_fork_epoch: 0
  eip7805_fork_epoch: 1
  seconds_per_slot: 6
  num_validator_keys_per_node: 256
snooper_enabled: true
additional_services:
  - dora
  - tx_fuzz
  - spamoor
port_publisher:
  additional_services:
    enabled: true
    public_port_start: 65500
spamoor_params:
  spammers:
    - scenario: eoatx
      config:
        throughput: 100
    - scenario: uniswap-swaps
      config:
        throughput: 100
    - scenario: blob-combined
      config:
        throughput: 5
