participants:
  - el_type: geth
    el_image: geth-focil:latest
    cl_type: prysm
    cl_image: prysm-beacon-chain-focil:latest
    vc_type: prysm
    vc_image: prysm-validator-focil:latest
    count: 2
network_params:
  genesis_delay: 20
  fulu_fork_epoch: 0
  eip7805_fork_epoch: 1
  seconds_per_slot: 6
  perfect_peerdas_enabled: true
  num_validator_keys_per_node: 256
snooper_enabled: true
additional_services:
  - dora
  - tx_fuzz
  - spamoor
dora_params:
  image: ethpandaops/dora:eip7805-support-latest
port_publisher:
  additional_services:
    enabled: true
    public_port_start: 65500
spamoor_params:
  spammers:
    - scenario: eoatx
      config:
        throughput: 100
    - scenario: uniswap-swaps
      config:
        throughput: 100
    - scenario: blob-combined
      config:
        throughput: 5
