participants:
  - el_type: geth
    el_image: geth-focil:latest
    cl_type: prysm
    cl_image: prysm-beacon-chain-focil:latest
    vc_type: prysm
    vc_image: prysm-validator-focil:latest
    count: 2
network_params:
  genesis_delay: 20
  electra_fork_epoch: 1
  seconds_per_slot: 4
  num_validator_keys_per_node: 64
snooper_enabled: true
additional_services:
  - dora
  - tx_spammer
port_publisher:
  additional_services:
    enabled: true
    public_port_start: 65500
