participants_matrix:
  el:
    - el_type: besu
      el_image: ethpandaops/besu:focil
    - el_type: ethrex
      el_image: ethpandaops/ethrex:focil
  cl:
    - cl_type: lodestar
      cl_image: ethpandaops/lodestar:focil
    - cl_type: teku
      cl_image: ethpandaops/teku:focil
    - cl_type: lighthouse
	    cl_image: ethpandaops/lighthouse:focil
network_params:
  gloas_fork_epoch: 1
  heze_fork_epoch: 2
  num_validator_keys_per_node: 256
  preset: minimal
additional_services:
  - dora
  - tx_fuzz
  - spamoor
dora_params:
  image: bbusa/dora:focil
port_publisher:
  additional_services:
    enabled: true
    public_port_start: 65500
spamoor_params:
  spammers:
    - scenario: eoatx
      config:
        throughput: 100
    - scenario: uniswap-swaps
      config:
        throughput: 100
    - scenario: blob-combined
      config:
        throughput: 5
