participants:
  - el_type: geth
    el_image: jihoonsg/geth-focil:4ae0066
    cl_type: prysm
    cl_image: jihoonsg/prysm-beacon-chain-focil:ec28ad1
    vc_type: prysm
    vc_image: jihoonsg/prysm-validator-focil:ec28ad1
    count: 2
network_params:
  genesis_delay: 20
  electra_fork_epoch: 1
  fulu_fork_epoch: 2
  eip7805_fork_epoch: 3
  seconds_per_slot: 6
  num_validator_keys_per_node: 256
snooper_enabled: true
additional_services:
  - dora
  - tx_spammer
port_publisher:
  additional_services:
    enabled: true
    public_port_start: 65500
