participants_matrix:
  el:
    - el_type: geth
      el_image: jihoonsg/geth-focil:9d17826
  cl:
    - cl_type: prysm
      cl_image: jihoonsg/prysm-beacon-chain-focil:9d26fe2
      vc_type: prysm
      vc_image: jihoonsg/prysm-validator-focil:9d26fe2
      supernode: true
    - cl_type: lodestar
      cl_image: ethpandaops/lodestar:focil-aed75aa
    - cl_type: teku
      cl_image: ethpandaops/teku:focil
    - cl_type: lighthouse
      cl_image: jihoonsg/lighthouse-focil:92c22ed
network_params:
  genesis_delay: 20
  fulu_fork_epoch: 0
  eip7805_fork_epoch: 1
  seconds_per_slot: 6
  num_validator_keys_per_node: 256
snooper_enabled: true
additional_services:
  - dora
  - tx_fuzz
  - spamoor
dora_params:
  image: ethpandaops/dora:eip7805-support-latest
port_publisher:
  additional_services:
    enabled: true
    public_port_start: 65500
spamoor_params:
  spammers:
    - scenario: eoatx
      config:
        throughput: 100
    - scenario: uniswap-swaps
      config:
        throughput: 100
    - scenario: blob-combined
      config:
        throughput: 5
