participants:
  - el_type: geth
    el_image: jihoonsg/geth-focil:78f8ad9
    cl_type: prysm
    cl_image: jihoonsg/prysm-beacon-chain-focil:4b0a8ad
    vc_type: prysm
    vc_image: jihoonsg/prysm-validator-focil:4b0a8ad
    count: 2
network_params:
  genesis_delay: 20
  electra_fork_epoch: 1
  seconds_per_slot: 4
  num_validator_keys_per_node: 64
snooper_enabled: true
additional_services:
  - dora
port_publisher:
  additional_services:
    enabled: true
    public_port_start: 65500
