participants_matrix:
  el:
    - el_type: ethrex
      el_image: ethpandaops/ethrex:focil-devnet-0
    - el_type: besu
      el_image: ethpandaops/besu:focil-devnet-0
    - el_type: nethermind
      el_image: ethpandaops/nethermind:focil-devnet-0
  cl:
    - cl_type: lodestar
      cl_image: ethpandaops/lodestar:focil-devnet-0
    - cl_type: teku
      cl_image: ethpandaops/teku:focil-devnet-0
network_params:
  preset: mainnet
  gloas_fork_epoch: 0
  heze_fork_epoch: 1
additional_services:
  - dora
  - spamoor
port_publisher:
  additional_services:
    enabled: true
    public_port_start: 65500
spamoor_params:
  spammers:
    - scenario: eoatx
      config:
        throughput: 100
    - scenario: uniswap-swaps
      config:
        throughput: 100
    # - scenario: blob-combined
    #   config:
    #     throughput: 5
global_log_level: debug
