participants:
  - el_type: geth
    el_image: jihoonsg/geth-focil:no-osaka
    cl_type: prysm
    cl_image: prysm-beacon-chain-focil:latest
    vc_type: prysm
    vc_image: prysm-validator-focil:latest
  - el_type: geth
    el_image: jihoonsg/geth-focil:no-osaka
    cl_type: lodestar
    cl_image: lodestar-focil:latest
network_params:
  genesis_delay: 20
  electra_fork_epoch: 0
  eip7805_fork_epoch: 1
  num_validator_keys_per_node: 256
snooper_enabled: true
additional_services:
  - dora
  - tx_fuzz
port_publisher:
  additional_services:
    enabled: true
    public_port_start: 65500
